services:
  - type: web
    name: infraction-commune-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: infraction-commune-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: infraction-commune-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: infraction-commune-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: infraction-commune-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: infraction-commune-db
          property: password

  databases:
  - name: infraction-commune-db
    engine: POSTGRES
    version: "15"
    plan: free
    region: frankfurt
    databaseName: infraction_commune
